### ISSUE TITLE
where should i put the tutorials?

### ISSUE THREAD

**Issue by lee2sman** [publicityreform/findbyimage#7]
Maybe we should have a category called Class Tutorials?

**Comment by publicityreform** [comment]
totally - right now it's called "howto", but "class tutorials" or whatever makes the most sense, yes!

**Comment by lee2sman** [comment]
do you manually add sub-categories (not sure of difference btwn category and tag i think!).

i am thinking these howto's should go in _posts like normal?

**Comment by publicityreform** [comment]
howto's can definitely be posts, with a category. that's done in the front matter. tags too - i was thinking tags would just be freeform, anything mentioned in the post that's worth indexing.

**Comment by publicityreform** [comment]
i've made "howto" a category and merged all the markdown files in `howto` into the `_posts` directory, and added yaml frontmatter so they now function as posts - the same as the other categories (`notes` and eventually `projects`)
